// Catalog of connector types available when adding a source.
// capabilities: 'scan' = can be scanned for record-type discovery; 'search' = can be queried for records.
// purpose: groups access methods by what the user is trying to accomplish (see Source Linking UI).
//   live = query a system in place (discovery aid) · storage = document file storage ·
//   av = audio/video storage · import = bring files IN to index/redact/publish ·
//   paper = physical records index · demo = demonstration
module.exports = [
  { key:'import', label:'Import — file drop', purpose:'import', description:'Bring files INTO the system so they can be extracted, indexed, redacted, and published. A folder where another system\'s export job drops files (push), or a location the system pulls from on a schedule. NOTE: the ingestion pipeline is being built - you can configure the source now; it will begin ingesting once that ships.', capabilities:[], fields:[ { key:'path', label:'Drop folder / import path', type:'text', placeholder:'/opt/optimumq/imports/payroll' }, { key:'mode', label:'Mode (push or pull)', type:'text', placeholder:'push' } ] },
  { key:'filestore', label:'Network Drive / Folder', purpose:'storage', description:'A folder of documents (PDFs) on a mounted drive or local path. Scannable for record-type discovery.', capabilities:['scan'], fields:[ { key:'path', label:'Folder path', type:'text', placeholder:'/opt/optimumq/sample_repo' } ] },
  { key:'structured', label:'Structured System', purpose:'live', description:'A system whose records are defined by a schema and sample rows (JSON definition). Scannable for record-type discovery.', capabilities:['scan'], fields:[ { key:'path', label:'System definition (JSON path)', type:'text', placeholder:'/opt/optimumq/sample_systems/payroll.json' } ] },
  { key:'tyler', label:'Tyler Munis (Financial / ERP)', purpose:'live', description:'Tyler Munis ERP connector for financial and procurement records.', capabilities:['search'], fields:[ { key:'endpoint', label:'API endpoint URL', type:'text' }, { key:'api_key', label:'API key', type:'text' } ] },
  { key:'laserfiche', label:'Laserfiche ECM', purpose:'live', description:'Laserfiche enterprise content management connector. The citywide document repository spanning most departments and many record series; searched and enumerated via API (not a scannable folder).', capabilities:['search'], fields:[ { key:'endpoint', label:'Repository API URL', type:'text' }, { key:'api_key', label:'API key', type:'text' } ] },
  { key:'axon', label:'Axon Evidence', purpose:'av', description:'Axon digital evidence connector for police records (audio/video).', capabilities:['search'], fields:[ { key:'endpoint', label:'API endpoint URL', type:'text' }, { key:'api_key', label:'API key', type:'text' } ] },
  { key:'paper-index', label:'Paper Records Index', purpose:'paper', description:'An index of physical/paper records held in a storage location. Searching returns the physical location of a record rather than a downloadable file; retrieval is handled manually. Import the index after adding the source.', capabilities:['search'], fields:[ { key:'facility', label:'Storage facility (optional)', type:'text', placeholder:'City Records Center' } ] },
  { key:'nena911', label:'911 Call Management System (demo)', purpose:'live', description:'Computer-aided dispatch (911) call records. A synthetic CAD emulator that generates call records flowing through born-redacted structured redaction (caller identity withheld; incident type/location/time/disposition public).', capabilities:['search'], fields:[] },
  { key:'demo', label:'Demo Document Library', purpose:'demo', description:'Built-in demonstration document set.', capabilities:['search'], fields:[] }
];
