'use strict';
// GENERATE THE DETERMINISTIC FIXTURE — src/db/seed_fixture.sql
//
//   node src/db/gen_fixture_seed.js        # regenerate from the live config
//
// WHY: the test fixture used to be a CLONE OF LIVE, taken at run time. That works, but it means the tests
// inherit whatever happens to be in production today — the fixture is not a fixed thing you can review, and a
// config change in live silently changes what the suite is asserting against. This emits a single reviewable,
// version-controlled SQL file instead. Same input every run, and a diff when it changes.
//
// It is ALSO the install seed: schema.postgres.sql + seed_fixture.sql is a working system from empty, which is
// what a new city gets. (The old seed_* files had drifted from live and cover only part of the config; they are
// superseded by this. See the (yt) HANDOFF entry.)
//
// WHAT GOES IN: reference/config data only — the taxonomy, the org chart, the rules, the jurisdictions.
// WHAT STAYS OUT: every transactional row (requests, tasks, history, clocks, payments, files, embeddings) and
// the demo corpus. A fixture that ships 126 requests and 3,200 demo emails is not a fixture, it is a backup.
//
// SECRETS ARE NEVER WRITTEN. Password hashes, MFA secrets, and any api-key-shaped system_config value are
// emitted as NULL/empty. This file goes into git; nothing sensitive may ride along.
require('dotenv').config({ path: '/opt/optimumq/backend/.env' });
const { Pool } = require('pg');
const fs = require('fs');
const path = require('path');

// Order matters: parents before children, because the fixture loads with FKs ARMED. If this list is wrong the
// load fails loudly, which is the point — a fixture that needs deferred constraints is hiding a broken graph.
const REFERENCE_TABLES = [
  'system_config',
  'decision_reasons',
  'function_roles',
  'permission_roles',
  'departments',
  'users',
  'user_function_roles',
  'user_permission_roles',
  'user_task_types',
  'categories',
  'record_types',
  'record_type_departments',
  'record_repositories',
  'record_type_repositories',
  'legal_sources',
  'jurisdiction_profiles',
  'jurisdiction_profile_sections',
  'jurisdiction_rules',
  // config_history is PROVENANCE, not a transaction log: it records how each config domain came to hold
  // the values it holds (no request link). verify_survey_seed asserts the 18 clarification policies arrived
  // through the real config path rather than being hand-inserted -- an anti-cheat check that only means
  // anything if the provenance travels WITH the config.
  'config_history',
  'rule_legal_sources',
  'redaction_categories',
  'redaction_rules',
  'fee_profiles',
  'fee_matrix',
  'workflow_rules',
  'agent_rules',
  'layout_profiles',
];

// Columns that must NEVER be written to a file that goes into git.
const SECRET_COLUMNS = { users: ['password_hash', 'mfa_secret'] };
// system_config is key/value; redact anything that smells like a credential.
const SECRET_KEY_RE = /(key|secret|token|password|credential|dsn|url)/i;

function lit(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (v instanceof Date) return "'" + v.toISOString() + "'";
  if (typeof v === 'object') return "'" + JSON.stringify(v).replace(/'/g, "''") + "'";
  return "'" + String(v).replace(/'/g, "''") + "'";
}

(async () => {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const out = [];
  let redacted = 0;

  out.push('-- AUTO-GENERATED by src/db/gen_fixture_seed.js. Do not edit by hand; regenerate.');
  out.push('-- The deterministic fixture: reference/config data only. No requests, no tasks, no demo corpus,');
  out.push('-- no secrets. schema.postgres.sql + this file = a working system from an EMPTY database.');
  out.push('');

  for (const table of REFERENCE_TABLES) {
    const { rows: colRows } = await pool.query(
      "SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 ORDER BY ordinal_position",
      [table]
    );
    if (!colRows.length) { console.log('  SKIP (no such table):', table); continue; }
    const cols = colRows.map((c) => c.column_name);

    // Deterministic order: sort by every column, so the file is byte-stable across regenerations.
    const orderBy = cols.map((_, i) => (i + 1)).join(', ');
    const { rows } = await pool.query('SELECT * FROM "' + table + '" ORDER BY ' + orderBy);
    if (!rows.length) { out.push('-- ' + table + ': (empty)'); out.push(''); continue; }

    const secrets = SECRET_COLUMNS[table] || [];
    const values = rows.map((row) => {
      const vals = cols.map((c) => {
        if (secrets.includes(c) && row[c] != null) { redacted++; return 'NULL'; }
        if (table === 'system_config' && c === 'value' && SECRET_KEY_RE.test(String(row.key)) && row[c]) {
          redacted++;
          return "''"; // key preserved so the install knows the slot exists; the value must be set locally
        }
        return lit(row[c]);
      });
      return '  (' + vals.join(', ') + ')';
    });

    out.push('INSERT INTO "' + table + '" (' + cols.map((c) => '"' + c + '"').join(', ') + ') VALUES');
    out.push(values.join(',\n') + '\nON CONFLICT DO NOTHING;');
    out.push('');
    console.log('  ' + table.padEnd(32) + rows.length + ' rows');
  }

  const target = path.join(__dirname, 'seed_fixture.sql');
  fs.writeFileSync(target, out.join('\n'));
  await pool.end();
  console.log('\nwrote ' + target);
  console.log('redacted ' + redacted + ' secret value(s) — password hashes, MFA secrets, credential-shaped config');
})().catch((e) => { console.error('gen_fixture_seed FAILED:', e.message); process.exit(1); });
