PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS system_config (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT DEFAULT (datetime('now')));
INSERT OR IGNORE INTO system_config (key, value) VALUES ('auth_mode','local'),('agency_name','City of Optimum'),('fee_threshold','40.00'),('mfa_mode','optional');
CREATE TABLE IF NOT EXISTS departments (id TEXT PRIMARY KEY, name TEXT NOT NULL, code TEXT UNIQUE NOT NULL, color TEXT DEFAULT '#2E75B6', is_open_records INTEGER DEFAULT 0, is_catch_all INTEGER DEFAULT 0, sort_order INTEGER DEFAULT 0, active INTEGER DEFAULT 1);
INSERT OR IGNORE INTO departments (id,name,code,color,is_open_records,is_catch_all,sort_order) VALUES ('dept-openrecords','Open Records','OR','#1F4E79',1,0,0),('dept-clerk','City Clerk','CC','#2E75B6',0,1,1),('dept-building','Building & Planning','BP','#5B9BD5',0,0,2),('dept-attorney','City Attorney','CA','#843C0C',0,0,3),('dept-finance','Finance & Accounting','FA','#375623',0,0,4),('dept-it','Information Technology','IT','#7030A0',0,0,5),('dept-police','Police Department','PD','#1F3864',0,0,6),('dept-publicworks','Public Works','PW','#7F6000',0,0,7);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, display_name TEXT NOT NULL, title TEXT, department_id TEXT, password_hash TEXT, mfa_secret TEXT, mfa_enrolled INTEGER DEFAULT 0, temp_password INTEGER DEFAULT 0, status TEXT DEFAULT 'active', last_login TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS function_roles (id TEXT PRIMARY KEY, name TEXT UNIQUE NOT NULL, sort_order INTEGER DEFAULT 0);
INSERT OR IGNORE INTO function_roles (id,name,sort_order) VALUES ('fr-coordinator','COORDINATOR',1),('fr-supervisor','SUPERVISOR',2),('fr-feewaiver','FEE_WAIVER_APPROVER',3),('fr-redactionreviewer','REDACTION_REVIEWER',4),('fr-redactionapprover','REDACTION_APPROVER',5),('fr-attorney','ATTORNEY_REVIEWER',6),('fr-custodian','CUSTODIAN',7),('fr-deptmanager','DEPT_MANAGER',8),('fr-director','DIRECTOR',9),('fr-sysadmin','SYSTEM_ADMIN',10);
CREATE TABLE IF NOT EXISTS permission_roles (id TEXT PRIMARY KEY, name TEXT UNIQUE NOT NULL);
INSERT OR IGNORE INTO permission_roles (id,name) VALUES ('pr-reqmgr','REQUEST_MANAGER'),('pr-searchtriage','SEARCH_AND_TRIAGE'),('pr-redworker','REDACTION_WORKER'),('pr-redauth','REDACTION_AUTHORITY'),('pr-feemgr','FEE_MANAGER'),('pr-feeauth','FEE_AUTHORITY'),('pr-clarify','CLARIFICATION_SENDER'),('pr-delivery','DELIVERY_AND_CLOSURE'),('pr-denial','DENIAL_AND_LEGAL'),('pr-escalation','ESCALATION_HANDLER'),('pr-reopen','REQUEST_REOPENER');
CREATE TABLE IF NOT EXISTS user_function_roles (user_id TEXT NOT NULL, function_role_id TEXT NOT NULL, PRIMARY KEY (user_id, function_role_id));
CREATE TABLE IF NOT EXISTS user_permission_roles (user_id TEXT NOT NULL, permission_role_id TEXT NOT NULL, PRIMARY KEY (user_id, permission_role_id));
-- Per-person routable task-type subset (v3 role model). Eligibility = active + on team + subset includes the task type.
CREATE TABLE IF NOT EXISTS user_task_types (user_id TEXT NOT NULL, task_type TEXT NOT NULL, PRIMARY KEY (user_id, task_type));
CREATE TABLE IF NOT EXISTS requests (id TEXT PRIMARY KEY, request_number TEXT UNIQUE NOT NULL, is_mrr INTEGER DEFAULT 0, master_request_id TEXT, component_label TEXT, requestor_name TEXT NOT NULL, requestor_email TEXT NOT NULL, requestor_phone TEXT, requestor_type TEXT DEFAULT 'individual', delivery_method TEXT DEFAULT 'email', description TEXT NOT NULL, record_types TEXT, classification TEXT DEFAULT 'standard', department_id TEXT, assigned_to TEXT, stage TEXT DEFAULT 'intake', status TEXT DEFAULT 'active', closure_reason TEXT, fee_waiver_requested INTEGER DEFAULT 0, estimated_fee REAL DEFAULT 0, actual_fee REAL DEFAULT 0, amount_paid REAL DEFAULT 0, legal_flag INTEGER DEFAULT 0, legal_flag_type TEXT, deadline_date TEXT, submission_channel TEXT DEFAULT 'portal', fee_waiver_reason TEXT, mailing_street1 TEXT, mailing_street2 TEXT, mailing_city TEXT, mailing_state TEXT, mailing_zip TEXT, certification_requested INTEGER DEFAULT 0, email_verification_method TEXT, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_requests_stage ON requests(stage);
CREATE INDEX IF NOT EXISTS idx_requests_dept ON requests(department_id);
CREATE INDEX IF NOT EXISTS idx_requests_status ON requests(status);
CREATE TABLE IF NOT EXISTS request_history (id TEXT PRIMARY KEY, request_id TEXT NOT NULL, actor_id TEXT, actor_name TEXT NOT NULL, action TEXT NOT NULL, details TEXT, notes TEXT, stage_from TEXT, stage_to TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS fee_matrix (id TEXT PRIMARY KEY, category TEXT NOT NULL, description TEXT, rate REAL NOT NULL, unit TEXT NOT NULL, is_active INTEGER DEFAULT 1, sort_order INTEGER DEFAULT 0);
INSERT OR IGNORE INTO fee_matrix (id,category,description,rate,unit,sort_order) VALUES ('fee-research','Research Time','Staff time for research',15.00,'per_hour',1),('fee-photocopy','Photocopying','Paper copies per page',0.10,'per_page',2),('fee-electronic','Electronic Media','USB or electronic media',3.00,'per_item',3);

CREATE TABLE IF NOT EXISTS request_files (id TEXT PRIMARY KEY, request_id TEXT NOT NULL, filename TEXT NOT NULL, original_name TEXT NOT NULL, mimetype TEXT, size INTEGER, status TEXT DEFAULT 'attached', responsive INTEGER DEFAULT 0, uploaded_by TEXT, uploaded_at TEXT DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_files_request ON request_files(request_id);
