-- Property & Assets record types. Idempotent via ON CONFLICT (code).
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-property-deeds','cat-property','City property & real estate records','property-deeds','City-owned real property and title records.','Record city-owned real property and title records.','Property description, ownership, acquisition, deeds, and parcel data.','Requested to identify city-owned land and real estate holdings.','["deed","city property","real estate","land records","property record"]','["not private property tax records","not leases"]','["deed","property","real estate","parcel","title"]','["property address or parcel","instrument number","date"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,10),
('rt-asset-inventory','cat-property','Fixed asset & equipment inventory','asset-inventory','List of city-owned fixed assets and equipment.','List city-owned fixed assets and equipment.','Asset description, identifier, location, value, and acquisition date.','Requested to review what equipment and assets the city owns.','["asset inventory","fixed assets","equipment list","capital assets"]','["not the vehicle fleet only","not surplus disposal"]','["asset","inventory","equipment","fixed asset","capital"]','["asset type","identifier","department","acquisition date"]','["structured_data"]',1,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,20),
('rt-leases-easements','cat-property','Leases & easements','leases-easements','Leases and easements involving city property.','Record leases and easements involving city property.','Parties, property, term, rent or consideration, and conditions.','Requested to review agreements over city land or facilities.','["lease","easement","license agreement","right of way","ground lease"]','["not property deeds","not vendor contracts"]','["lease","easement","right of way","tenant","term"]','["property or location","parties","instrument number","term"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,30),
('rt-surplus-disposal','cat-property','Surplus property & disposal','surplus-disposal','Declaration and disposal of surplus city property.','Record the declaration and disposal of surplus city property.','Items, valuation, method of disposal, buyers, and proceeds.','Requested to review how the city disposes of surplus assets.','["surplus","auction","disposal","asset disposal","surplus property"]','["not the active asset inventory","not procurement"]','["surplus","disposal","auction","sale","proceeds"]','["item or lot","disposal date","method"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,40),
('rt-property-appraisals','cat-property','Property appraisals & acquisitions','property-appraisals','Appraisals and records for property the city acquires.','Hold appraisals and records for property the city acquires.','Appraised value, negotiations, and acquisition documents.','Requested regarding a city property acquisition or its value.','["appraisal","acquisition","property valuation","condemnation","right of way acquisition"]','["not a recorded deed","not asset inventory"]','["appraisal","acquisition","valuation","negotiation","condemnation"]','["property address or parcel","project","date"]','["document"]',0,'review_required',0,NULL,0,0,'Appraisals and negotiation records may be withheld while acquisition is pending.',0,'active','seed',NULL,50)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-property-deeds-own','rt-property-deeds','dept-finance','owner',10),
('rd-asset-inventory-own','rt-asset-inventory','dept-finance','owner',10),
('rd-leases-easements-own','rt-leases-easements','dept-finance','owner',10),
('rd-surplus-disposal-own','rt-surplus-disposal','dept-finance','owner',10),
('rd-property-appraisals-own','rt-property-appraisals','dept-finance','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
