-- Elections & Vital Records record types. Idempotent via ON CONFLICT (code).
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-election-results','cat-elections','Election results & canvass','election-results','Official election results and canvass records.','Provide official election results and canvass records.','Vote totals by contest and precinct, canvass, and certification.','Requested by candidates, media, and the public for election outcomes.','["election results","canvass","vote totals","returns","official results"]','["not voter registration","not campaign finance"]','["election","results","canvass","votes","returns"]','["election date","contest","precinct"]','["document","structured_data"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,10),
('rt-campaign-finance','cat-elections','Campaign finance reports','campaign-finance','Campaign finance filings by candidates and committees.','Provide campaign finance filings by candidates and committees.','Contributions, expenditures, and filer information from required reports.','Requested to review money in local campaigns.','["campaign finance","contributions","expenditure report","finance report","campaign filing"]','["not election results","not candidate petitions"]','["campaign finance","contribution","expenditure","filing","committee"]','["candidate or committee","reporting period","election"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,20),
('rt-voter-registration','cat-elections','Voter registration records','voter-registration','Voter registration records and rolls.','Hold voter registration records and rolls.','Registered voter information and rolls, with regulated access and use.','Requested by campaigns and researchers, subject to use restrictions.','["voter registration","voter rolls","voter list","registration records","voter file"]','["not election results","not candidate filings"]','["voter","registration","rolls","list","file"]','["precinct or area","as-of date"]','["structured_data"]',1,'restricted',0,NULL,0,0,'Access and permitted use are regulated; some data is restricted or withheld.',0,'active','seed',NULL,30),
('rt-candidate-filings','cat-elections','Candidate filings & petitions','candidate-filings','Candidate applications, filings, and petitions for office.','Record candidate applications, filings, and petitions for office.','Applications for a place on the ballot, petitions, and eligibility filings.','Requested to verify who filed for office and their paperwork.','["candidate filing","ballot application","petition","candidacy","nomination"]','["not campaign finance","not election results"]','["candidate","filing","petition","ballot","application"]','["candidate","office","election date"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,40),
('rt-vital-records','cat-elections','Vital records (birth, death, marriage)','vital-records','Birth, death, and marriage records maintained by the city.','Hold birth, death, and marriage records maintained by the city.','Certificates and registers of births, deaths, and marriages.','Requested by eligible persons for a certified vital record.','["vital records","birth certificate","death certificate","marriage license","marriage record"]','["not voter registration","not court records"]','["vital","birth","death","marriage","certificate"]','["record type","name","date","certificate number"]','["document"]',0,'confidential',0,NULL,0,0,'Access is limited to eligible persons under strict statutory rules.',0,'active','seed',NULL,50)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-election-results-own','rt-election-results','dept-clerk','owner',10),
('rd-campaign-finance-own','rt-campaign-finance','dept-clerk','owner',10),
('rd-voter-registration-own','rt-voter-registration','dept-clerk','owner',10),
('rd-candidate-filings-own','rt-candidate-filings','dept-clerk','owner',10),
('rd-vital-records-own','rt-vital-records','dept-clerk','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
