-- Finance & Procurement record types. Idempotent via ON CONFLICT (code).
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-budgets','cat-finance','Budgets & financial reports','budgets','Adopted budgets and annual financial reports.','Provide the adopted budget or annual financial report for a fiscal year.','Revenues, expenditures, fund balances, and budget detail by department and fiscal year.','Requested by residents, researchers, and watchdogs reviewing city spending and finances.','["budget","annual budget","CAFR","ACFR","financial report","comprehensive annual financial report"]','["not individual invoices","not check registers"]','["budget","CAFR","ACFR","fiscal year","appropriation"]','["fiscal year","fund","department"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,10),
('rt-financial-audits','cat-finance','Financial audits','financial-audits','Independent and internal audit reports of city finances.','Provide an audit report examining city financial operations.','Auditor findings, opinions, management responses, and corrective action plans.','Requested to review the financial health and accountability of the city.','["audit","audit report","financial audit","single audit","auditor report"]','["not the budget","not internal investigations"]','["audit","auditor","findings","opinion"]','["fiscal year","audit type","department or fund"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,20),
('rt-check-registers','cat-finance','Check registers & expenditures','check-registers','Records of payments and expenditures made by the city.','Provide records of city payments to vendors and individuals.','Payee, amount, date, fund, and purpose of payments; structured expenditure data.','Requested to see who the city paid, how much, and for what.','["check register","expenditures","vendor payments","disbursements","payment history"]','["not vendor contracts","not invoices themselves"]','["check","payment","expenditure","vendor","disbursement"]','["date range","vendor or payee","fund or department"]','["structured_data"]',1,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,30),
('rt-purchasing-contracts','cat-finance','Purchasing & vendor contracts','purchasing-contracts','Contracts and agreements with vendors for goods and services.','Provide a contract or agreement between the city and a vendor.','Parties, scope, term, pricing, signatures, and amendments of a vendor agreement.','Requested to review what the city bought, from whom, and on what terms.','["contract","vendor contract","agreement","purchase agreement","service contract"]','["not construction contracts","not settlement agreements","not bids"]','["contract","vendor","agreement","procurement","amendment"]','["vendor name","contract number","date or term","subject"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,40),
('rt-bids-rfps','cat-finance','Bids, RFPs & proposals','bids-rfps','Solicitations and the bids or proposals received in response.','Provide a solicitation and the bids or proposals submitted for it.','RFP or bid documents, submitted proposals, pricing, evaluations, and award decisions.','Requested by bidders, competitors, and the public reviewing a procurement.','["bid","RFP","RFQ","proposal","solicitation","tender"]','["not the executed contract","not invoices"]','["bid","RFP","proposal","solicitation","award"]','["solicitation number","project or subject","date"]','["document"]',0,'review_required',0,NULL,0,0,'Submitted proposals may contain trade secrets; some are withheld until award.',0,'active','seed',NULL,50)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-budgets-own','rt-budgets','dept-finance','owner',10),
('rd-financial-audits-own','rt-financial-audits','dept-finance','owner',10),
('rd-check-registers-own','rt-check-registers','dept-finance','owner',10),
('rd-purchasing-contracts-own','rt-purchasing-contracts','dept-finance','owner',10),
('rd-bids-rfps-own','rt-bids-rfps','dept-finance','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
