-- Legal & Risk record types. Idempotent via ON CONFLICT (code).
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-settlements','cat-legal','Settlement agreements','settlements','Agreements settling claims or lawsuits involving the city.','Record the settlement of a claim or lawsuit involving the city.','Parties, settlement amount, terms, and release language.','Requested to see how much the city paid to settle a matter and why.','["settlement","settlement agreement","release","payout"]','["not active litigation files","not insurance claims"]','["settlement","agreement","release","payout","claim"]','["parties","case or matter number","date","amount"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,10),
('rt-litigation-files','cat-legal','Litigation & case files','litigation-files','City legal files for lawsuits and disputes.','Hold the city legal files for a lawsuit or dispute.','Pleadings, attorney work product, strategy, and correspondence; often privileged.','Requested regarding a lawsuit involving the city, frequently exempt.','["litigation","case file","lawsuit","legal file","pleadings"]','["not a final settlement","not a public court docket"]','["litigation","lawsuit","case","pleadings","privilege"]','["case name or number","court","date"]','["document"]',0,'confidential',0,NULL,0,0,'Attorney-client privilege and work product commonly apply.',0,'active','seed',NULL,20),
('rt-liability-claims','cat-legal','Claims against the city','liability-claims','Claims or demands for damages made against the city.','Record a claim or demand for damages made against the city.','Claimant, incident, alleged damages, investigation, and disposition.','Requested regarding an incident or a pattern of claims against the city.','["claim","tort claim","liability claim","damage claim","notice of claim"]','["not a finalized settlement","not litigation files"]','["claim","liability","tort","damages","incident"]','["claimant","claim number","date","incident"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,30),
('rt-legal-opinions','cat-legal','Legal opinions & memos','legal-opinions','Legal advice and analysis from the city attorney.','Provide legal advice and analysis from the city attorney.','Legal questions, analysis, and recommendations; typically privileged.','Requested to understand the legal basis for a city action or position.','["legal opinion","attorney opinion","legal memo","advice memo"]','["not adopted ordinances","not litigation files"]','["opinion","legal","memo","advice","privilege"]','["subject","date","requesting party"]','["document"]',0,'confidential',0,NULL,0,0,'Attorney-client privileged advice is generally confidential.',0,'active','seed',NULL,40),
('rt-insurance-risk','cat-legal','Insurance & risk records','insurance-risk','City insurance policies and risk management records.','Hold city insurance policies and risk management records.','Policies, coverage, certificates, and risk assessments.','Requested to verify coverage or review the city risk program.','["insurance","policy","coverage","risk management","certificate of insurance"]','["not individual claims","not settlements"]','["insurance","policy","coverage","risk","certificate"]','["policy number","carrier","coverage type","period"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,50)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-settlements-own','rt-settlements','dept-attorney','owner',10),
('rd-litigation-files-own','rt-litigation-files','dept-attorney','owner',10),
('rd-liability-claims-own','rt-liability-claims','dept-attorney','owner',10),
('rd-legal-opinions-own','rt-legal-opinions','dept-attorney','owner',10),
('rd-insurance-risk-own','rt-insurance-risk','dept-attorney','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
