-- Technology & Information Systems record types. Idempotent via ON CONFLICT (code).
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-it-security-policies','cat-technology','IT & security policies','it-security-policies','City technology and information security policies.','State the city technology and information security policies.','Policies on acceptable use, security, data handling, and system administration.','Requested to understand city IT and security practices.','["IT policy","security policy","acceptable use","data policy","information security"]','["not cybersecurity incident records","not system data"]','["IT","security","policy","acceptable use","data"]','["policy title","topic","effective date"]','["document"]',0,'review_required',0,NULL,0,0,'Security details that could expose vulnerabilities may be withheld.',0,'active','seed',NULL,10),
('rt-cybersecurity-incidents','cat-technology','Cybersecurity & incident records','cybersecurity-incidents','Records of cybersecurity incidents and the city response.','Record cybersecurity incidents and the city response.','Incident details, affected systems, response, and remediation; security-sensitive.','Requested regarding a data breach or cybersecurity incident.','["cybersecurity","breach","incident","security incident","data breach"]','["not routine IT policies","not system inventory"]','["cybersecurity","breach","incident","attack","remediation"]','["incident date","affected system","incident number"]','["document"]',0,'confidential',0,NULL,0,0,'Disclosure could expose vulnerabilities; generally confidential.',0,'active','seed',NULL,20),
('rt-gis-mapping-data','cat-technology','GIS & mapping data','gis-mapping-data','Geographic information system data and maps.','Provide geographic information system data and maps.','Map layers, parcels, infrastructure, and spatial datasets.','Requested by researchers, developers, and the public for spatial data.','["GIS","mapping data","map layers","spatial data","geographic data"]','["not infrastructure engineering plans","not zoning decisions"]','["GIS","map","spatial","layer","geographic"]','["layer or dataset","area","format"]','["structured_data"]',1,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,30),
('rt-system-data-exports','cat-technology','System data exports & reports','system-data-exports','Data exports or reports from city systems and databases.','Provide data exports or reports from city systems and databases.','Exported datasets and reports; content and sensitivity vary by system.','Requested for data held in a specific city system or database.','["data export","database report","data set","system report","data dump"]','["not GIS map layers","not financial check registers"]','["data","export","database","report","dataset"]','["system or database","fields or report","date range"]','["structured_data"]',1,'review_required',0,NULL,0,0,'Sensitivity depends on the underlying data; review required.',0,'active','seed',NULL,40)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-it-security-policies-own','rt-it-security-policies','dept-it','owner',10),
('rd-cybersecurity-incidents-own','rt-cybersecurity-incidents','dept-it','owner',10),
('rd-gis-mapping-data-own','rt-gis-mapping-data','dept-it','owner',10),
('rd-system-data-exports-own','rt-system-data-exports','dept-it','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
