-- Human Resources & Personnel record types. Idempotent via ON CONFLICT (code). No owner dept in demo.
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-personnel-files','cat-hr','Employee personnel files','personnel-files','Personnel files of city employees.','Provide the personnel file or employment records of a city employee.','Employment history, evaluations, certifications, and personnel actions; largely protected.','Requested regarding a specific employee, often with most contents exempt from release.','["personnel file","employee file","employment record","HR file"]','["not salary data alone","not disciplinary records alone"]','["personnel","employee","employment","HR","file"]','["employee name","department","date range"]','["document"]',0,'confidential',0,NULL,0,0,'Most contents are confidential under personnel-file exemptions; limited elements may be public.',0,'active','seed',NULL,10),
('rt-salary-compensation','cat-hr','Salaries & compensation','salary-compensation','Salary, wage, and compensation data for public employees.','Provide compensation data for city employees or positions.','Employee or position, title, salary or hourly rate, and total compensation.','Requested by media, unions, and the public reviewing public-employee pay.','["salary","compensation","pay","wages","payroll data","salary schedule"]','["not full personnel files","not benefits enrollment detail"]','["salary","pay","compensation","wages","payroll"]','["employee or position","department","fiscal year"]','["structured_data"]',1,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,20),
('rt-employee-roster','cat-hr','Employee roster & directory','employee-roster','Roster of city employees with positions and departments.','Provide a list of city employees, their titles, and departments.','Names, job titles, departments, and hire dates of public employees.','Requested to see who works for the city and in what roles.','["roster","directory","employee list","staff list","org chart"]','["not salary detail","not personnel files"]','["roster","directory","employees","staff","positions"]','["department","date","position"]','["structured_data"]',1,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,30),
('rt-disciplinary-records','cat-hr','Disciplinary & grievance records','disciplinary-records','Records of employee discipline and grievances.','Document disciplinary actions and grievances involving city employees.','Allegations, investigations, findings, discipline imposed, and grievance outcomes.','Requested regarding the conduct or discipline of a city employee.','["disciplinary record","grievance","reprimand","suspension","termination record"]','["not police internal affairs","not full personnel files"]','["discipline","grievance","reprimand","suspension","misconduct"]','["employee name","department","date","action"]','["document"]',0,'confidential',0,NULL,0,0,NULL,0,'active','seed',NULL,40),
('rt-recruitment-hiring','cat-hr','Recruitment & hiring records','recruitment-hiring','Job postings, applications, and hiring records.','Document recruitment for a position and the hiring process.','Job postings, applications, interview materials, and selection records.','Requested by applicants or the public reviewing a hiring decision.','["job posting","application","hiring records","recruitment","selection records"]','["not personnel files of current staff","not salary schedules"]','["recruitment","hiring","application","posting","selection"]','["position","department","posting or requisition number","date"]','["document"]',0,'review_required',0,NULL,0,0,'Job postings are generally public; applications contain applicant personal data requiring review.',0,'active','seed',NULL,50)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-personnel-files-own','rt-personnel-files','dept-hr','owner',10),
('rd-salary-compensation-own','rt-salary-compensation','dept-hr','owner',10),
('rd-employee-roster-own','rt-employee-roster','dept-hr','owner',10),
('rd-disciplinary-records-own','rt-disciplinary-records','dept-hr','owner',10),
('rd-recruitment-hiring-own','rt-recruitment-hiring','dept-hr','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
