-- Planning, Zoning & Land Use record types. Idempotent via ON CONFLICT (code).
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-zoning-records','cat-planning','Zoning records & maps','zoning-records','Zoning designations, maps, and regulations for property.','Identify the zoning designation and regulations for property.','Zoning district, map, permitted uses, and standards for a parcel or area.','Requested by owners, developers, and buyers checking how land may be used.','["zoning","zoning map","zoning designation","land use district"]','["not a plat","not a building permit"]','["zoning","district","land use","map","designation"]','["property address or parcel","zoning district","area"]','["document","structured_data"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,10),
('rt-plats-subdivisions','cat-planning','Plats & subdivision records','plats-subdivisions','Recorded plats and the division of land into lots.','Record the division of land into lots and the recorded plat.','Subdivision name, lot and block layout, dimensions, and recording data.','Requested by surveyors, owners, and developers researching parcels.','["plat","subdivision","plat map","final plat","lot and block"]','["not a site plan","not a zoning map"]','["plat","subdivision","lot","block","survey"]','["subdivision name","lot and block","recording or case number"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,20),
('rt-site-plans','cat-planning','Site plans & development applications','site-plans','Proposed development layouts and applications submitted for approval.','Show the proposed development and site layout submitted for approval.','Site layout, buildings, parking, drainage, and application materials.','Requested by neighbors, developers, and the public reviewing a project.','["site plan","development application","plan review","development plan"]','["not a plat","not a building permit"]','["site plan","development","application","layout","review"]','["project name or address","application number","date"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,30),
('rt-variances-rezoning','cat-planning','Variances & rezoning','variances-rezoning','Requests and decisions to vary or change zoning.','Record requests and decisions to vary or change zoning.','Application, staff report, hearing records, and the decision or conditions.','Requested to follow a rezoning or variance affecting a property or area.','["variance","rezoning","zoning change","special use permit","conditional use"]','["not the base zoning map","not a building permit"]','["variance","rezoning","special use","conditional use","hearing"]','["property address","case number","date","request type"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,40),
('rt-comprehensive-plan','cat-planning','Comprehensive & master plans','comprehensive-plan','Long-range plans guiding city growth and land use.','State the long-range plan guiding city growth and land use.','Goals, policies, future land use maps, and supporting studies.','Requested by residents, developers, and researchers reviewing city planning.','["comprehensive plan","master plan","general plan","future land use","strategic plan"]','["not parcel-specific zoning","not a site plan"]','["comprehensive plan","master plan","future land use","policy","growth"]','["plan name","adoption date","element or chapter"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,50)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-zoning-records-own','rt-zoning-records','dept-building','owner',10),
('rd-plats-subdivisions-own','rt-plats-subdivisions','dept-building','owner',10),
('rd-site-plans-own','rt-site-plans','dept-building','owner',10),
('rd-variances-rezoning-own','rt-variances-rezoning','dept-building','owner',10),
('rd-comprehensive-plan-own','rt-comprehensive-plan','dept-building','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
