-- Public Works & Utilities record types. Idempotent via ON CONFLICT (code).
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-construction-contracts','cat-public-works','Capital & construction contracts','construction-contracts','Contracts for public construction and capital improvement projects.','Contract for a public construction or capital improvement project.','Project scope, contractor, pricing, bonds, change orders, and timeline.','Requested to review who is building public projects and at what cost.','["construction contract","capital project","public works contract","CIP contract"]','["not vendor purchasing contracts","not engineering plans"]','["construction","capital","project","contractor","bond"]','["project name","contract number","contractor","date"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,10),
('rt-infrastructure-plans','cat-public-works','Infrastructure & engineering plans','infrastructure-plans','Engineering drawings and as-built plans for public infrastructure.','Provide engineering drawings and as-built plans for public infrastructure.','Drawings for roads, water, sewer, and drainage; as-builts and specifications.','Requested by engineers, contractors, and utilities locating infrastructure.','["as-built","engineering plans","construction drawings","infrastructure plans","utility plans"]','["not a development site plan","not a zoning map"]','["engineering","as-built","drawings","infrastructure","plans"]','["project or location","plan or sheet number","date"]','["document"]',0,'review_required',0,NULL,0,0,'Critical-infrastructure detail may be withheld or require review.',0,'active','seed',NULL,20),
('rt-utility-billing','cat-public-works','Utility billing records','utility-billing','Customer utility accounts, usage, and billing.','Record customer utility accounts, usage, and billing.','Account holder, service address, consumption, charges, and payment history.','Requested by account holders regarding their own utility service.','["utility bill","water bill","billing record","account history","usage"]','["not the citywide rate schedule","not work orders"]','["utility","billing","water","sewer","account"]','["account holder","service address","account number","period"]','["structured_data"]',1,'confidential',0,NULL,0,0,'Customer account and usage data are generally confidential.',0,'active','seed',NULL,30),
('rt-work-orders','cat-public-works','Work orders & service requests','work-orders','Maintenance and service requests and the work performed.','Record maintenance and service requests and the work performed.','Request type, location, date, status, and crew or action taken.','Requested to track repairs and responses such as potholes or water leaks.','["work order","service request","maintenance request","311 request"]','["not a construction contract","not utility billing"]','["work order","service request","maintenance","repair","311"]','["location or address","request or ticket number","date","type"]','["structured_data"]',1,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,40),
('rt-water-quality','cat-public-works','Water quality & testing reports','water-quality','Drinking water quality and testing results.','Report drinking water quality and testing results.','Sampling results, contaminant levels, and compliance with standards.','Requested by residents and researchers concerned about water safety.','["water quality","CCR","consumer confidence report","water testing","water sampling"]','["not utility billing","not infrastructure plans"]','["water quality","testing","contaminant","sampling","CCR"]','["reporting period","system or location","contaminant"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,50)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-construction-contracts-own','rt-construction-contracts','dept-publicworks','owner',10),
('rd-infrastructure-plans-own','rt-infrastructure-plans','dept-publicworks','owner',10),
('rd-utility-billing-own','rt-utility-billing','dept-publicworks','owner',10),
('rd-work-orders-own','rt-work-orders','dept-publicworks','owner',10),
('rd-water-quality-own','rt-water-quality','dept-publicworks','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
