-- Governance & Legislative record types. Idempotent via ON CONFLICT (code).
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-council-agendas','cat-governance','City council agendas','council-agendas','Posted agendas for city council meetings.','Provide the posted agenda for a council meeting.','Meeting date, agenda items, order of business, and supporting agenda packet references.','Requested by residents, journalists, and applicants tracking what the council will consider.','["agenda","council agenda","meeting agenda","agenda packet"]','["not the minutes","not the meeting recording"]','["agenda","council","meeting","packet"]','["meeting date","body or committee","agenda item"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,10),
('rt-council-minutes','cat-governance','City council minutes','council-minutes','Official approved minutes of city council meetings.','Provide the official minutes recording actions taken at a council meeting.','Attendance, motions, votes, and actions taken; the official record of the meeting.','Requested for the official record of decisions, votes, and discussion.','["minutes","council minutes","meeting minutes","record of proceedings"]','["not the agenda","not the recording"]','["minutes","council","votes","motions"]','["meeting date","body or committee","action or item"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,20),
('rt-meeting-recordings','cat-governance','Meeting recordings','meeting-recordings','Audio or video recordings of public meetings.','Provide the audio or video recording of a public meeting.','Recorded proceedings of council, board, or commission meetings open to the public.','Requested to hear or see what was said during a public meeting.','["meeting video","council video","meeting audio","broadcast","webcast"]','["not the written minutes","not closed-session content"]','["recording","video","audio","webcast","broadcast"]','["meeting date","body or committee","agenda item"]','["video","audio"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,30),
('rt-ordinances','cat-governance','Ordinances','ordinances','Adopted city ordinances and the local code.','Provide an adopted ordinance or codified local law.','The text of an ordinance, its number, adoption date, and subject matter.','Requested to find the law on a topic or the text of a specific ordinance.','["ordinance","city code","municipal code","local law","code of ordinances"]','["not a resolution","not a policy"]','["ordinance","code","law","chapter","section"]','["ordinance number","subject","adoption date"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,40),
('rt-resolutions','cat-governance','Resolutions','resolutions','Adopted city council resolutions.','Provide an adopted council resolution.','The text of a resolution, its number, adoption date, and subject matter.','Requested to find a specific resolution or council position on a matter.','["resolution","council resolution","proclamation"]','["not an ordinance","not the minutes"]','["resolution","adopted","council"]','["resolution number","subject","adoption date"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,50),
('rt-boards-commissions','cat-governance','Boards & commissions records','boards-commissions','Records of city boards, commissions, and committees.','Provide agendas, minutes, and membership records for a board or commission.','Agendas, minutes, rosters, and appointment records for advisory and regulatory bodies.','Requested to follow the work of a specific board, commission, or committee.','["board","commission","committee","advisory board","appointments"]','["not the city council itself","not staff departments"]','["board","commission","committee","appointment","roster"]','["body name","meeting date","member name"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,60)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-council-agendas-own','rt-council-agendas','dept-clerk','owner',10),
('rd-council-minutes-own','rt-council-minutes','dept-clerk','owner',10),
('rd-meeting-recordings-own','rt-meeting-recordings','dept-clerk','owner',10),
('rd-ordinances-own','rt-ordinances','dept-clerk','owner',10),
('rd-resolutions-own','rt-resolutions','dept-clerk','owner',10),
('rd-boards-commissions-own','rt-boards-commissions','dept-clerk','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
