-- Police & Law Enforcement record types (11). Idempotent via ON CONFLICT (code).
-- Apply: cat seed_rt_police.sql | docker exec -i optimumq-postgres psql -U optimumq -d optimumq
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-incident-reports','cat-police','Incident / offense reports','incident-reports','Reported crime, complaint, or incident with the responding officer narrative.','Document a reported crime, complaint, or incident and the responding officer narrative.','Officer narrative, parties involved (reporting party, victims, suspects, witnesses), offense type, date, time, and location.','Requested by victims, insurers, attorneys, journalists, or involved parties seeking the official account of an incident.','["police report","offense report","crime report","incident report","case report"]','["not a traffic crash report","not a 911 recording","not a citation"]','["incident","offense","complaint","report number","case number"]','["incident or case number","date","location","parties involved","offense type"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,10),
('rt-arrest-booking','cat-police','Arrest & booking records','arrest-booking','Arrest and booking of an individual into custody.','Record an arrest and the booking of an individual into custody.','Arrestee identity, charges, arrest date, time, location, arresting officer, booking number, and mugshot.','Requested by media, attorneys, background checkers, or the public regarding a specific arrest.','["arrest report","booking report","booking record","mugshot","jail booking"]','["not an incident report","not a citation"]','["arrest","booking","charges","mugshot","custody"]','["arrestee name","arrest date","case or booking number","charges"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,20),
('rt-crash-reports','cat-police','Crash / accident reports','crash-reports','Motor-vehicle traffic crash investigated by the agency.','Document a motor-vehicle traffic crash investigated by the agency.','Crash date, time, location, vehicles and drivers involved, diagram, contributing factors, injuries, and citations issued; in Texas the standardized CR-3 form.','Requested by involved drivers, insurers, and attorneys to process claims.','["accident report","crash report","CR-3","collision report","wreck report"]','["not a general incident report","not a citation"]','["crash","accident","collision","CR-3","traffic"]','["crash date","location","driver or party names","crash or report number"]','["document"]',0,'review_required',0,NULL,0,0,'Often released to involved parties; some jurisdictions charge a set fee per report.',0,'active','seed',NULL,30),
('rt-citations','cat-police','Citations & traffic tickets','citations','Citation or ticket issued for a traffic or municipal violation.','Record a citation or ticket issued for a traffic or municipal violation.','Cited individual, violation code and description, date, time, location, issuing officer, and fine amount.','Requested by the cited party, attorneys, or for records of enforcement activity.','["ticket","traffic ticket","citation","violation notice"]','["not a crash report","not an arrest record"]','["citation","ticket","violation","fine"]','["cited name","citation number","date","violation"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,40),
('rt-police-video','cat-police','Body-worn & in-car (dash) camera footage','police-video','Body-worn and in-car (dash) camera recordings of officer activity.','Capture audio-visual recording of events an officer is directly involved in while on duty, from body-worn or in-car cameras.','Footage of officer interactions with citizens, suspects, and witnesses; traffic stops; arrests; and scene activity.','Requested when officer conduct is in question, such as use of force or a wrongful arrest claim, or to document a specific incident.','["body cam","bodycam","BWC","body-worn camera","dash cam","in-car video","police video"]','["not surveillance or CCTV footage","not 911 audio"]','["body camera","dash camera","footage","video","recording"]','["date","location","officers involved","incident or case number"]','["video"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,50),
('rt-911-recordings','cat-police','911 call recordings','911-recordings','Audio of a 911 or non-emergency call as placed by the caller.','Capture the audio of a 911 or non-emergency call as placed by the caller.','The caller voice, what they reported, dispatcher questions, background audio, and call timing.','Requested to hear what a caller said or reported about a specific incident.','["911 call","911 audio","911 recording","emergency call recording","call audio"]','["not the CAD or dispatch log","not body-cam audio"]','["911","emergency call","recording","audio","caller"]','["call date and time","phone number","address","incident or call number"]','["audio"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,60),
('rt-cad-logs','cat-police','Dispatch / call-for-service logs (CAD)','cad-logs','Computer-aided-dispatch metadata and response history for a call for service.','Record the dispatch metadata and response history for a call for service, from the computer-aided-dispatch system.','Call type, timestamps, units dispatched, response and clear times, disposition codes, and location; structured data, not audio.','Requested to see how a call was handled, response times, or call history at an address.','["CAD log","dispatch log","call for service","CFS","incident history"]','["not the 911 audio recording","not the incident report narrative"]','["dispatch","CAD","call for service","disposition","response time"]','["date and time","address","call or incident number","call type"]','["structured_data"]',1,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,70),
('rt-use-of-force','cat-police','Use-of-force reports','use-of-force','Officer use of force during an encounter and the administrative review.','Document officer use of force during an encounter and the agency review of it.','Description of the force used, the circumstances, subjects involved, injuries, and supervisory review.','Requested in connection with misconduct concerns, oversight, or litigation.','["use of force report","UOF","force report","response to resistance"]','["not an internal affairs complaint file","not an incident report"]','["use of force","UOF","response to resistance"]','["date","officers","subject","incident or case number"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,80),
('rt-internal-affairs','cat-police','Internal affairs / misconduct complaints & investigations','internal-affairs','Complaints against personnel and the internal investigation and findings.','Record complaints against personnel and the agency internal investigation and findings.','Complaint details, named officers, investigative steps, evidence, findings, and any discipline; frequently confidential or exempt.','Requested regarding allegations of officer misconduct or patterns of complaints.','["internal affairs","IA file","misconduct complaint","professional standards","citizen complaint"]','["not a use-of-force report alone","not a general personnel file"]','["internal affairs","misconduct","complaint","investigation","discipline"]','["officer name","complaint or IA number","date","disposition"]','["document"]',0,'restricted',0,NULL,0,0,NULL,0,'active','seed',NULL,90),
('rt-crime-stats','cat-police','Crime statistics & data','crime-stats','Aggregate crime and enforcement data compiled by the agency.','Provide aggregate crime and enforcement data compiled by the agency.','Counts and trends of offenses, calls, arrests, and clearances by category, area, and time period; aggregate, not individual records.','Requested by researchers, journalists, and the public for crime trends and transparency.','["crime stats","crime data","UCR","NIBRS","crime statistics"]','["not individual incident reports","not personally identifiable"]','["statistics","crime data","trends","UCR","NIBRS"]','["time period","geographic area","offense category"]','["structured_data"]',1,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,100),
('rt-police-policies','cat-police','Police policies & general orders','police-policies','Department policies, procedures, and general orders.','State the department policies, procedures, and general orders governing operations.','Written policies, standard operating procedures, and general orders on conduct, use of force, pursuits, and other operations.','Requested for transparency, oversight, or to understand departmental rules.','["general orders","police policy","SOP","department policy","standard operating procedure"]','["not a specific incident record","not case-specific training materials"]','["policy","general order","SOP","procedure","manual"]','["policy title or number","topic","effective date"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,110)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, fee_estimate_note=EXCLUDED.fee_estimate_note,
  source=EXCLUDED.source, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');

-- Owner department links (Police owns all; fulfiller defaults to owner unless set elsewhere)
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-incident-reports-own','rt-incident-reports','dept-police','owner',10),
('rd-arrest-booking-own','rt-arrest-booking','dept-police','owner',10),
('rd-crash-reports-own','rt-crash-reports','dept-police','owner',10),
('rd-citations-own','rt-citations','dept-police','owner',10),
('rd-police-video-own','rt-police-video','dept-police','owner',10),
('rd-911-recordings-own','rt-911-recordings','dept-police','owner',10),
('rd-cad-logs-own','rt-cad-logs','dept-police','owner',10),
('rd-use-of-force-own','rt-use-of-force','dept-police','owner',10),
('rd-internal-affairs-own','rt-internal-affairs','dept-police','owner',10),
('rd-crime-stats-own','rt-crime-stats','dept-police','owner',10),
('rd-police-policies-own','rt-police-policies','dept-police','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
