-- Permits, Licenses & Inspections record types. Idempotent via ON CONFLICT (code).
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-building-permits','cat-permits','Building permits','building-permits','Permits authorizing construction, alteration, or demolition.','Authorize construction, alteration, or demolition of a structure.','Permit number, property address, scope of work, valuation, contractor, and inspections.','Requested by owners, buyers, contractors, and neighbors checking permitted work.','["building permit","construction permit","permit record","remodel permit"]','["not a code violation case","not a certificate of occupancy"]','["permit","building","construction","valuation","contractor"]','["property address","permit number","date","permit type"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,10),
('rt-business-licenses','cat-permits','Business licenses & permits','business-licenses','Licenses authorizing a business or regulated activity to operate.','License a business or regulated activity to operate.','Business name, owner, license type, address, status, and dates.','Requested to verify a business is licensed or to research a company.','["business license","occupational license","permit to operate","business permit"]','["not a building permit","not a contractor registration"]','["business","license","permit","operate","registration"]','["business name","license number","address","license type"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,20),
('rt-inspection-reports','cat-permits','Inspection reports','inspection-reports','Inspections of properties or projects for code compliance.','Document an inspection of a property or project for code compliance.','Inspection type, date, inspector, results, and corrections required.','Requested by owners, buyers, and tenants checking inspection history.','["inspection report","code inspection","building inspection","health inspection"]','["not a fire marshal inspection","not a code violation case"]','["inspection","compliance","inspector","result","correction"]','["property address","inspection date","permit or case number","inspection type"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,30),
('rt-certificates-occupancy','cat-permits','Certificates of occupancy','certificates-occupancy','Certificates approving a structure for occupancy or use.','Certify a structure is approved for occupancy or use.','Property, approved use, issue date, and conditions.','Requested by owners, buyers, and tenants confirming legal occupancy.','["certificate of occupancy","CO","occupancy permit","use certificate"]','["not a building permit","not an inspection report"]','["occupancy","certificate","CO","use","approved"]','["property address","certificate number","issue date"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,40),
('rt-code-enforcement','cat-permits','Code enforcement cases','code-enforcement','Code violation cases and their enforcement.','Document a code violation case and its enforcement.','Property, alleged violation, notices, inspections, and resolution; may include complainant identity.','Requested by owners, neighbors, and buyers researching property violations.','["code violation","code enforcement","nuisance case","compliance case"]','["not a building permit","not a routine inspection"]','["code","violation","enforcement","nuisance","complaint"]','["property address","case number","date","violation type"]','["document"]',0,'review_required',0,NULL,0,0,'Complainant identity and open enforcement details may require review.',0,'active','seed',NULL,50)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
INSERT INTO record_type_departments (id, record_type_id, department_id, role, sort_order) VALUES
('rd-building-permits-own','rt-building-permits','dept-building','owner',10),
('rd-business-licenses-own','rt-business-licenses','dept-building','owner',10),
('rd-inspection-reports-own','rt-inspection-reports','dept-building','owner',10),
('rd-certificates-occupancy-own','rt-certificates-occupancy','dept-building','owner',10),
('rd-code-enforcement-own','rt-code-enforcement','dept-building','owner',10)
ON CONFLICT (record_type_id, department_id, role) DO NOTHING;
