-- Correspondence & Communications record types. Idempotent via ON CONFLICT (code). No single owner dept.
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-official-email','cat-communications','Official email correspondence','official-email','Email sent or received by city officials and staff on city business.','Capture official email sent or received by city officials and staff.','Messages and attachments related to city business, with senders, recipients, and dates.','Requested to see communications on a topic, often needing custodian and date scoping.','["email","emails","correspondence","electronic mail","messages"]','["not text messages","not press releases"]','["email","correspondence","inbox","sent","message"]','["custodian or sender","recipients","date range","subject or keywords"]','["document"]',0,'review_required',0,NULL,0,0,'Often requires custodian and date-range scoping; deliberative and personal content may be withheld.',0,'active','seed',NULL,10),
('rt-text-messages','cat-communications','Text & instant messages','text-messages','Text or instant messages about city business.','Capture text or instant messages about city business.','SMS or chat messages on official matters, with participants and timing.','Requested to see messaging about a topic or decision.','["text message","SMS","texts","instant message","chat messages"]','["not email","not social media posts"]','["text","SMS","message","chat","instant message"]','["participant","date range","subject or keywords"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,20),
('rt-social-media','cat-communications','Social media records','social-media','Public social media posts and content from official accounts.','Capture the city public social media posts and content.','Public posts, images, and published content from official accounts.','Requested to review the city public social media communications.','["social media","posts","Facebook","Twitter","Instagram","tweets"]','["not private messages or DMs","not email"]','["social media","post","tweet","account","published"]','["account or platform","date range","topic"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,30),
('rt-press-releases','cat-communications','Press releases & public statements','press-releases','Official press releases and public statements.','Provide official press releases and public statements.','Issued releases, statements, and media advisories with dates and topics.','Requested to review official announcements and public messaging.','["press release","public statement","media advisory","announcement","news release"]','["not internal memos","not social media"]','["press release","statement","media","announcement","news"]','["title or topic","release date"]','["document"]',0,'releasable',1,NULL,0,0,NULL,0,'active','seed',NULL,40),
('rt-internal-memos','cat-communications','Internal memos & correspondence','internal-memos','Internal memos and correspondence among city staff.','Capture internal memos and correspondence among city staff.','Memos, letters, and notes on city business among staff and departments.','Requested to see internal communications on a matter.','["memo","memorandum","internal correspondence","staff memo","interoffice"]','["not email threads","not press releases"]','["memo","memorandum","correspondence","internal","note"]','["author","date","subject"]','["document"]',0,'review_required',0,NULL,0,0,'Deliberative pre-decisional content may be withheld.',0,'active','seed',NULL,50)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
