-- Fire & EMS record types. Idempotent via ON CONFLICT (code). No owner dept in demo.
INSERT INTO record_types (id, category_id, name, code, description, intent, expected_content, typical_request_reason, synonyms, disambiguators, keywords, identifying_facets, formats, is_structured_data, public_availability, auto_release_eligible, redaction_profile_id, fee_estimate_low, fee_estimate_high, fee_estimate_note, is_canonical, status, source, confidence, sort_order) VALUES
('rt-fire-incident-reports','cat-fire-ems','Fire incident reports','fire-incident-reports','Reports documenting fire department responses to fires and incidents.','Document a fire department response to a fire, hazard, or emergency incident.','Incident type, location, units responding, narrative, damage, and injuries; often the NFIRS report.','Requested by property owners, insurers, and attorneys regarding a fire or response.','["fire report","NFIRS","incident report","fire run report"]','["not an EMS patient report","not an arson investigation"]','["fire","incident","NFIRS","response","run"]','["incident number","date","location","property"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,10),
('rt-ems-patient-records','cat-fire-ems','EMS patient care reports','ems-patient-records','Patient care reports from emergency medical responses.','Document the medical care provided during an EMS response.','Patient assessment, treatment, vitals, and transport details; protected health information.','Requested by patients or their representatives regarding medical care received.','["EMS report","patient care report","PCR","ambulance report","medical report"]','["not a fire incident report","not a 911 recording"]','["EMS","patient","medical","ambulance","PCR"]','["incident number","date","patient name"]','["document"]',0,'confidential',0,NULL,0,0,'Protected health information; release governed by HIPAA and limited to eligible persons.',0,'active','seed',NULL,20),
('rt-fire-inspection-reports','cat-fire-ems','Fire inspection reports','fire-inspection-reports','Fire marshal inspections of buildings and facilities for code compliance.','Document a fire safety inspection and any code violations found.','Inspection date, facility, inspector, findings, violations, and corrective actions.','Requested by building owners, tenants, buyers, and businesses checking compliance.','["fire inspection","fire marshal report","code inspection","safety inspection"]','["not a building permit inspection","not an incident report"]','["inspection","fire marshal","compliance","violation"]','["facility or address","inspection date","permit or case number"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,30),
('rt-fire-investigation','cat-fire-ems','Fire cause & arson investigations','fire-investigation','Investigations into the cause and origin of fires, including suspected arson.','Document the investigation into how a fire started and whether it was intentional.','Origin and cause findings, evidence, witness statements, and arson determinations.','Requested regarding the cause of a fire, often by insurers or involved parties.','["arson investigation","cause and origin","fire investigation","origin report"]','["not a routine fire incident report","not an inspection"]','["arson","cause","origin","investigation","fire"]','["incident number","date","location"]','["document"]',0,'review_required',0,NULL,0,0,NULL,0,'active','seed',NULL,40)
ON CONFLICT (code) DO UPDATE SET
  category_id=EXCLUDED.category_id, name=EXCLUDED.name, description=EXCLUDED.description,
  intent=EXCLUDED.intent, expected_content=EXCLUDED.expected_content,
  typical_request_reason=EXCLUDED.typical_request_reason, synonyms=EXCLUDED.synonyms,
  disambiguators=EXCLUDED.disambiguators, keywords=EXCLUDED.keywords,
  identifying_facets=EXCLUDED.identifying_facets, formats=EXCLUDED.formats,
  is_structured_data=EXCLUDED.is_structured_data, public_availability=EXCLUDED.public_availability,
  auto_release_eligible=EXCLUDED.auto_release_eligible, sort_order=EXCLUDED.sort_order,
  updated_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS');
